return {
	"nvim-treesitter/nvim-treesitter",
	desc = "Syntax highlighting and parsing",
	build = ":TSUpdate",
	event = { "BufReadPost", "BufNewFile", "BufWritePre", "VeryLazy" },
	opts = {
		ensure_installed = {
			"javascript",
			"typescript",
			"tsx",
			"html",
			"css",
			"java",
			"rust",
			"python",
			"json",
			"xml",
			"yaml",
			"bash",
			"lua",
			"markdown",
			"markdown_inline",
		},
		highlight = { enable = true },
		indent = { enable = true },
	},
}
